name: tutorial_2
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: Erik <email@example.com>

environment:
  sdk: '>=2.0.0-dev.32.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha
  http: ^0.11.0
  jsonpadding: ^0.1.0
  stream_transform: ^0.0.5

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.8
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^0.12.35